services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_project_CICD
    ports:
      - 8500:8500
    environment:
      - REST_API_SERVICE_NAME=rest_backend_project_CICD:9000
    depends_on:
      - backend-rest
    networks:
      - frontend

  backend-rest:
    build:
      context: ./backend/rest-api
      dockerfile: Dockerfile
    container_name: rest_backend_project_CICD
    # ports:
    #   - 9000:9000
    environment:
      - INFERENCE_API_SERVICE_NAME=inference_backend_project_CICD:8000
    depends_on:
      - backend-inference
    networks:
      - frontend
      - backend

  backend-inference:
    build:
      context: ./backend/onnx-inference
      dockerfile: Dockerfile
    container_name: inference_backend_project_CICD
    # ports:
    #   - 8000:8000
    networks:
      - backend

networks:
  frontend:
  backend:
